management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mysql:///personal_work_test?character=UTF-8
    username: root
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.personalwork.modal.entity,com.personalwork.modal.query,com.personalwork.modal.dto
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*
  type-handlers-package: com.personalwork.constants
server:
  port: 8082
