
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
mybatis-plus:
  type-aliases-package: com.personalwork.domain.entity,com.personalwork.domain.query,com.personalwork.domain.dto
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*
  type-handlers-package: com.personalwork.constants
